#!/usr/bin/python

import os
import sys
import sagemaker
from sagemaker.tensorflow import TensorFlow
sess = sagemaker.Session()

BUCKET_NAME_SOURCE = os.environ.get('SRC_BKT_NAME')
BUCKET_NAME_OUTPUT = os.environ.get('OUTPUT_BKT')
PREFIX = 'input/data/training/'

inputs = 's3://' + BUCKET_NAME_SOURCE + '/' + PREFIX

def train():
    print('Starting the training.')
    try:
        abalone_estimator = TensorFlow(entry_point='abalone.py',
                                    role=os.environ.get('SM_ROLE'),
                                    framework_version='2.1.0',
                                    output_path='s3://' + BUCKET_NAME_OUTPUT,
                                    training_steps= 100,                                  
                                    evaluation_steps= 100,
                                    hyperparameters={'learning_rate': 0.001},
                                    train_instance_count=1,
                                       sagemaker_session=sess,
                                    train_instance_type='ml.c4.xlarge')

        abalone_estimator.fit(inputs)
    except Exception as e:
        print('Exception during training: ' + str(e))

if __name__ == '__main__':
    train()

    sys.exit(0)
